# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileSearch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploadImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_file', models.FileField(upload_to='uploads')),
            ],
        ),
        migrations.DeleteModel(
            name='smiles',
        ),
    ]
